name: Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16.10.0"
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Run Code Formatter
        run: npm run format -- --check

      - name: Run Firefox Extension Linter
        run: |
          npm run prod
          npm run lint
